apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
spec:
  generators:
  - list:
      elements:
      - cluster: do-lon1-engineering-dev
        url: https://e5cfeb55-77ce-44bb-b209-7f872f9e8018.k8s.ondigitalocean.com
      - cluster: do-lon1-engineering-prod
        url: https://64d20718-444a-4c76-94ee-f613f20724e6.k8s.ondigitalocean.com
  template:
    metadata:
      namespace: argocd
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - "apps/{{path[2]}}/{{path.basename}}/values.yaml"
            - "apps/{{path[2]}}/values.yaml"
        path: demo
        repoURL: https://github.com/shariqmus/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
      destination:
        # specify different destinations
        namespace: "{{path.basename}}"
        server: '{{url}}'
